### PR TITLE
Bookshelf repo

### PR DESCRIPTION
**Pull request by RayRoyal76**

### CODE REVIEW

**Review by sjoseph11236 — CHANGES_REQUESTED** [review]
You're missing the @Repository annotation

**Comment by RayRoyal76** [comment]
Added repository annotation

**Review by RayRoyal76 — COMMENTED** [review]
Added Annotation

**Review by sjoseph11236 — CHANGES_REQUESTED** [review]
The Id type should be Long not Integer

**Comment by RayRoyal76** [comment]
Id type has been changed to Long

**Review by sjoseph11236 — CHANGES_REQUESTED** [review]
A Repository should be an interface

**Comment by RayRoyal76** [comment]
Changed to Interface

**Review by sjoseph11236 — APPROVED** [review]

**Pull request merged**
